name: Install yq
description: "Install yq"
runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      run: |
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
